{-
The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
-}

triangle :: Int -> Int
triangle x = sum [1..x]

divisors :: Int -> Int
divisors x = length [y | y <- [1..(div x 2)] ++ [x], mod x y == 0]

answer :: Int -> Int -> Int
answer x limit
	| (divisors $ triangle x) > limit = triangle x
	| otherwise = answer (x + 1) limit

main = putStrLn $ show $ answer 1 50